import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :bezgelor_portal, BezgelorPortalWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  server: true,
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "u/ReHup2hqcCCvBBEe1b9clm1TH3+TL31hVv0cTfr1SJJRWS3c/7fNFQPzt9dZ8g",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:bezgelor_portal, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:bezgelor_portal, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :bezgelor_portal, BezgelorPortalWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/bezgelor_portal_web/router\.ex$"E,
      ~r"lib/bezgelor_portal_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :bezgelor_portal, dev_routes: true

# Development logging configuration
#
# Console: info+ only (keeps output clean)
# File:    debug+ to rotating log (5MB x 3 files)
#
# Usage:
#   mix run --no-halt              # Clean console, debug in file
#   LOG_LEVEL=debug mix run        # Debug on console too
#   tail -f logs/dev.log           # Monitor debug output in real-time
#
# Configuration:
#   :logger, :console, level:      Console log level (default: info)
#   :bezgelor_core, :file_log      Rotating file log settings
config :logger,
  level: :debug

config :logger, :console,
  level: String.to_existing_atom(System.get_env("LOG_LEVEL", "info")),
  format: "[$level] $message\n"

# Rotating file log - captures all debug output for troubleshooting
# Console stays clean (info+), file gets everything (debug+)
config :bezgelor_core,
  file_log: [
    path: "logs/dev.log",
    max_bytes: 5_000_000,   # 5MB per file
    max_files: 3            # Keep 3 rotated files
  ]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Development-specific Repo configuration
config :bezgelor_db, BezgelorDb.Repo,
  show_sensitive_data_on_connection_error: true,
  stacktrace: true
